Update aspera-client-docker image to use the new download workflow
IDR/aspera-client-docker pull request #5
Opened 2023-12-19 09:00 UTC by sbesson

See https://github.com/IDR/idr.openmicroscopy.org/issues/190

This updates the source of the https://hub.docker.com/r/imagedata/download Docker image to use the new Aspera download workflow. Opens the discussion on whether the IDR team keeps supporting this image. Otherwise, it should probably be archived/deprecated

Included in this PR are the minimal change to make the command functional again

- Drops the study input in favor of the generic fasp-public user
- Update the README with the new command format
- Update the GitHub workflow

If the team decides to keep supporting this workflow, a possible set of additional upgrades up for discussion:
- upgrade the base image  to Ubuntu 22.04 or Rocky 9
- upgrade of the GitHub actions 
- upgrade of the Aspera command-line client

2023-12-19 09:43 UTC, joshmoore commented on README.md
> +where SOURCE can be any subfolder under https://ftp.ebi.ac.uk/pub/databases/IDR/. For instance
:heart:

2023-12-20 10:42 UTC, pwalczysko commented
Test 1 on Mac M1 - build and run the docker as-is in this PR, use the ``docker run...`` cmd from README and building an image ``test-seb``:

```
aspera-client-docker %  docker build -f Dockerfile --rm --no-cache -t test-seb . 
aspera-client-docker %  docker run -ti --rm -v /Users/pwalczysko:/data test-seb idr0001-graml-sysgro/20151116-verified/JL_120731_S6A /data/JL_120731_S6A 
/home/data/.aspera/connect/bin/ascp -P33001 -l 40m -i /home/data/.aspera/connect/etc/asperaweb_id_dsa.openssh -k 0 fasp-public@fasp.ebi.ac.uk:/pub/databases/IDR/idr0001-graml-sysgro/20151116-verified/JL_120731_S6A /data/JL_120731_S6A
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

As per https://stackoverflow.com/questions/71040681/qemu-x86-64-could-not-open-lib64-ld-linux-x86-64-so-2-no-such-file-or-direc/71611002#71611002, this ^^^ is caused by me being on M1. Went for a solution where I add the line into the Dockerfile ``FROM --platform=linux/amd64 centos:centos7``, saved the file as DockerfileM1 and build a new image ``test-sebm1``.  This works fine, see below.


```
aspera-client-docker % docker build -f DockerfileM1 --rm --no-cache -t test-sebm1 .
aspera-client-docker % docker run -ti --rm -v /Users/pwalczysko:/data test-sebm1 idr0001-graml-sysgro/20151116-verified/JL_120731_S6A /data/JL_120731_S6A
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
/home/data/.aspera/connect/bin/ascp -P33001 -l 40m -i /home/data/.aspera/connect/etc/asperaweb_id_dsa.openssh -k 0 fasp-public@fasp.ebi.ac.uk:/pub/databases/IDR/idr0001-graml-sysgro/20151116-verified/JL_120731_S6A /data/JL_120731_S6A
001005001.flex                                                     53%   47MB 38.9Mb/s    00:09 ETA
```

2023-12-20 10:56 UTC, pwalczysko commented
Is it reasonable to keep using centos7 images for this workflow ?

2023-12-20 10:58 UTC, pwalczysko requested changes
Two issues:
1. Please comment on the M1 support - imho, this type of platform is more and more prevalent and we could offer a solution in this repo.
2. centos7 ?

2023-12-20 11:59 UTC, sbesson commented
Last commit should allow to build the Linux/amd64 image independently on whether the build machine is `arm64` or `amd64`. Thanks @pwalczysko 

On the base image, I am of the opinion we should change it to either Ubuntu 22.04 or Rocky Linux 9 but am not opinionated on either of them. Happy to follow the guidance of the IDR team

2023-12-26 22:24 UTC, jburel commented
since the initial image was centOS 7, it might be more natural to switch to Rocky Linux 9

2024-01-03 10:45 UTC, pwalczysko commented
Tested last 2 commits (Rocky Linux 9 based image).

Works fine on 

   - Mac Apple M1 Pro
   - Mac amd64 (old laptop)

2024-01-03 10:45 UTC, pwalczysko approved these changes

2024-01-29 11:28 UTC, jburel approved these changes

2024-01-29 12:41 UTC, joshmoore approved these changes
:+1: (Here's to an `AND` vs `OR` option for the requested reviewers :wink:)

2024-01-29 13:20 UTC, sbesson commented
Unless someone wants to take the lead on this, I'll merge this PR by EOB and tag 0.4.0, hoping the deployment logic is still functional

2024-01-29 15:55 UTC, merged

2024-01-29 16:05 UTC, sbesson commented on .github/workflows/main.yml
> +          prefix: "${{ env.name }}"
Looks like I missed there was a breaking change and a `:` need to be appended as in https://github.com/ome/omero-server-docker/commit/6f317379d5a5d191200a491281862a334bd349c3.

Unfortunately, this has created quite a few unwanted images at https://hub.docker.com/u/imagedata. @jburel @joshmoore do you have the credentials to delete those? I can open a PR for a follow-up 0.4.1 release (unless you'd prefer me to delete the tag).